Controllers films users
kmmins/java-filmorate pull request #1
Opened 2023-01-23 22:50 UTC by kmmins

2023-01-24 07:10 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public String getName() {
хорошо

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final int id;
может сюда добавим валидационные аннотации, которые описаны в ТЗ

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
может сюда добавим валидационные аннотации, которые описаны в ТЗ

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/Validator.java
> +        if (film.getName().isEmpty() || film.getName().isBlank()) {
если используете аннотация, о которых я написал в Film и User, то эти методы можно сделать короче или вообще избавить от них

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/Validator.java
> +public class Validator {
тут давайте сделаем так: поставим аннотацию @Component - и можете Validator потом инжектить

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping("/films")
правильно что в одном месте указали

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Validator validator = new Validator();
смотрите коммент в Validator. Также используйте для полей модификатор доступа

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(FilmController.class);
вместо этого можете использовать аннотацию от ломбока @Slf4j

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmsDatabase.containsKey(film.getId())) {
сперва надо сделать валидацию

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmsDatabase.containsKey(film.getId())) {
сперва надо сделать валидацию

2023-01-24 07:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
смотрите комменты в FilmController

2023-01-25 14:49 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
И это тоже.

2023-01-25 14:49 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/Validator.java
> +        if (film.getName().isEmpty() || film.getName().isBlank()) {
И это.

2023-01-25 14:49 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/Validator.java
> +public class Validator {
И это.

2023-01-25 14:49 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Validator validator = new Validator();
И это.

2023-01-25 14:50 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(FilmController.class);
Здесь тоже.

2023-01-25 14:50 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmsDatabase.containsKey(film.getId())) {
Фикс.

2023-01-25 14:50 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmsDatabase.containsKey(film.getId())) {
Готово.

2023-01-25 14:50 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Все исправил вроде.

2023-01-26 05:01 UTC, ErkinKasymaliev approved these changes
работа принята

2023-01-28 15:39 UTC, merged