Add friends likes
kmmins/java-filmorate pull request #2
Opened 2023-02-05 21:12 UTC by kmmins

Здравствуйте. Посмотрите, пожалуйста, работу.

2023-02-06 06:01 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    //////////////////////////////////////////////методы filmStorage////////////////////////////////////////////////////
убрал лишние комментарии.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    //////////////////////////////////////////////методы filmStorage////////////////////////////////////////////////////
и это тоже.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userService.notContainsUser(userId)) {
изменил проверки и перенес выше.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userService.notContainsUser(userId)) {
и здесь.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    //////////////////////////////////////////////методы userStorage////////////////////////////////////////////////////
убрал.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void addFriend(int id1, int id2) {
назвал переменные по другому.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        var user2 = userStorage.getUserById(id2);
и эти.

2023-02-07 14:40 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (int e : thisUserFriendsSet) {
понял, принял.

2023-02-07 14:41 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    boolean notContainsFilm(int id);
вроде разобрался, вместо двух отдельных интерфейсов использовал один обобщенный.

2023-02-07 14:41 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public boolean notContainsFilm(int id) {
вспомогательные методы теперь имеют private доступ в классах storage.

2023-02-08 06:05 UTC, ErkinKasymaliev approved these changes
привет, отлично!
Работа принята!

2023-02-10 07:47 UTC, merged