Add database
kmmins/java-filmorate pull request #3
Opened 2023-03-05 21:18 UTC by kmmins

Здравствуйте, посмотрите, пожалуйста работу.

2023-03-06 17:39 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomExceptionHandler.java
> +    //400 Bad Request («неправильный, некорректный запрос»)
такого рода комменты не нужны, сразу видно за что отвечает метод)

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomExceptionHandler.java
>      public Map<String, String> handleIncorrectParameter(final IncorrectParameterException e) {
лучше вместо мапы используйте модель, назовите например, ErrorResponse

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("/films")
лучше оставьте как было - аннотацию над классом

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Genre> getAllGenre() {
создайте отдельный контроллер для жанров

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/mpa")
создайте отдельный контроллер для mpa

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping("/users")
лучше вынесите в @RequestMapping над классом

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private HashMap<Integer, Boolean> friendsMap;
просто Map

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        for (int userId : film.getLikesSet()) {
это думаю не совсем правильно с точки зрения бизнес логики. При создании фильма у него не может быть лайков. Лайки добавляем к существующим фильмам

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sql = "SELECT FILM_ID, FILM_NAME, DESCRIPTION, RELEASE_DATE, F.MPA_ID, M.CODE, DURATION FROM FILMS AS F INNER JOIN MPA AS M ON F.MPA_ID = M.MPA_ID";
жанры тоже надо заджойнить

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sql = "SELECT FILM_ID, FILM_NAME, DESCRIPTION, RELEASE_DATE, F.MPA_ID, M.CODE, DURATION FROM FILMS AS F INNER JOIN MPA AS M ON F.MPA_ID = M.MPA_ID WHERE FILM_ID = ?";
жанры тоже надо заджойнить

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String checkId = "SELECT FILM_ID FROM FILMS WHERE FILM_ID = ?";
эту проверку надо делать в сервисе

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            String sqlGenre = "SELECT FG.GENRE_ID, G.GENRE_NAME FROM FILM_GENRE AS FG INNER JOIN GENRE AS G ON FG.GENRE_ID = G.GENRE_ID WHERE FILM_ID = ?";
надо джойнить в запросах, здесь только маппите

2023-03-06 17:39 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        String checkEmail = "SELECT COUNT(*) AS SAME_MAIL FROM USERS WHERE EMAIL = ?";
все проверки должны быть в сервисе

2023-03-07 22:15 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomExceptionHandler.java
> +    //400 Bad Request («неправильный, некорректный запрос»)
Комментариев больше нет...

2023-03-07 22:16 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomExceptionHandler.java
>      public Map<String, String> handleIncorrectParameter(final IncorrectParameterException e) {
Теперь вместо мап ErrorResponse.

2023-03-07 22:17 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("/films")
вернул на место.

2023-03-07 22:18 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Genre> getAllGenre() {
новый контроллер добавлен.

2023-03-07 22:18 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/mpa")
и для mpa тоже.

2023-03-07 22:19 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private HashMap<Integer, Boolean> friendsMap;
исправил.

2023-03-07 22:19 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        for (int userId : film.getLikesSet()) {
у нового фильма больше нет лайков.

2023-03-07 22:20 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sql = "SELECT FILM_ID, FILM_NAME, DESCRIPTION, RELEASE_DATE, F.MPA_ID, M.CODE, DURATION FROM FILMS AS F INNER JOIN MPA AS M ON F.MPA_ID = M.MPA_ID";
Присоединил жанры к запросу.

2023-03-07 22:20 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sql = "SELECT FILM_ID, FILM_NAME, DESCRIPTION, RELEASE_DATE, F.MPA_ID, M.CODE, DURATION FROM FILMS AS F INNER JOIN MPA AS M ON F.MPA_ID = M.MPA_ID WHERE FILM_ID = ?";
и здесь.

2023-03-07 22:20 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String checkId = "SELECT FILM_ID FROM FILMS WHERE FILM_ID = ?";
проверки перенесены.

2023-03-07 22:21 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            String sqlGenre = "SELECT FG.GENRE_ID, G.GENRE_NAME FROM FILM_GENRE AS FG INNER JOIN GENRE AS G ON FG.GENRE_ID = G.GENRE_ID WHERE FILM_ID = ?";
RowMapper переработан.

2023-03-07 22:22 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            String sqlLikes = "SELECT USER_ID FROM FILMS_USERS_LIKES WHERE FILM_ID = ?";
sql-запрос исправлен, маппер тоже.

2023-03-07 22:22 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        String checkEmail = "SELECT COUNT(*) AS SAME_MAIL FROM USERS WHERE EMAIL = ?";
переработано, проверки перенесены.

2023-03-08 08:38 UTC, ErkinKasymaliev requested changes
привет, оставил 1 коммент

2023-03-08 08:38 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (id == null) {
@pathVariable нет смысла валидировать, так как если его не укажут, то сервер автоматически вернет not found. валидируются requestParams и headers можно. Уберите валидацию @PathVariable со всех контроллеров

2023-03-08 10:45 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (id == null) {
Убрал.

2023-03-09 10:23 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-13 08:47 UTC, merged